/*
 * VOUW - Generating, encoding and pattern-mining of Reduce-Fold Cellular Automata
 *
 * Micky Faas <micky@edukitty.org> 
 * Leiden Institute for Advanced Computer Science
 */

#include <stdio.h>
#include <stdbool.h>
#include <inttypes.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include "module.h"
#include "rfca.h"
#include "cli.h"

// Modules
#include "module_print.h"
#include "module_encode.h"

int
main( int _argc, char** _argv ) {

    int argc = _argc;
    char** argv = _argv;

    // The basic parameters specified from the commandline
    rfca_opts_t opts;
    opts.mode =MODE_DEFAULT;
    opts.right =false;
    opts.rule =0;
    opts.base =BASE_DEFAULT;
    opts.folds =FOLDS_DEFAULT;
    const char* param_module = NULL;

    // Add all module functions
    module_t modulePrint = {
        "print",
        "Prints the raw output generated by the automaton.",
        &module_print };
    module_register( &modulePrint );
    module_t moduleTTable = {
        "ttable",
        "Only print the transition table for a given configuration.",
        &module_printTTable };
    module_register( &moduleTTable );
    module_t moduleTTable2 = {
        "ttable2",
        "Print the level 2 transition table for a given configuration.",
        &module_printTTable2 };
    module_register( &moduleTTable2 );
    module_t moduleEncode = {
        "encode",
        "Place holder.",
        &module_encode };
    module_register( &moduleEncode );

    // The module is always the first argument
    if( argc == 1 ) {
        cli_printHelp( argv[0] );
        return 0;
    }
    param_module = argv[1];

    // Skip over the first two arguments (executable name and module)
    argv += 2;
    argc -= 2;

    if( !cli_parseOpts( &opts, &argv, &argc ) )
        return -1;

    if( !opts.inputSize ) {
        opts.inputSize = opts.mode;
        opts.input = (rfca_node_t*)malloc( sizeof( rfca_node_t ) * opts.inputSize );
        memset( opts.input, 0, opts.inputSize * sizeof( rfca_node_t ) );
    }

    int retval = module_call( param_module, opts, argc, argv );

    free( opts.input );
    return retval;

}
